env: 
#  ENCRYPTED
    CREDENTIALS: "ENCRYPTED[a80fb0b9f4917943337db3e22aa5c0d4b504d747321e0c6436c177259def1b8fe16dcf4e41d1897ae844cb6b47cb84b6]"
    USER_NAME: c3eru
    USER_EMAIL: yyprjkt@gmail.com
    BUILD_USER: builder
    BUILD_HOST: mobx-ci-task
    TG_TOKEN: "ENCRYPTED[1d38da8770169a63b4514480f061d96a7b0ccb76b4d655dc44cce7af3fd1bd2ef8a633bc484de605b656bd4c0b6384de]"
    TG_CHAT_ID: "ENCRYPTED[ebd5380589ed3f71a05b4ecaa1af01aac2444062051e0922ba56ec786e0d9551984834ddab8f4fa1a9d7856de11b9fa6]"
    
#  CIRRUS CONFIG
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
       
task:
  name: "Kernel Build.."
  timeout_in: 1h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G
      
  Credentials_script:
      - git config --global user.name "$USER_NAME"
      - git config --global user.email "$USER_EMAIL"
      - echo "$CREDENTIALS" > ~/.git-credentials
      - git config --global credential.helper store --file=~/.git-credentials
      - export TZ=Asia/Jakarta

  Sync_script:
      - ./sync.sh

  Clang-Proton_script:
      - ./proton-compile.sh

# Build 0
